# Generated by Django 4.0.3 on 2022-06-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('flatno', models.CharField(max_length=128, verbose_name='flatno')),
                ('street', models.CharField(blank=True, max_length=128, verbose_name='street')),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
