# Generated by Django 4.0.3 on 2022-06-16 11:57

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='registration',
            name='dob',
            field=models.DateField(),
        ),
    ]
